# 데이터
data_path: "/home/chanwoo/GPT_Feedback/data/feat_train_500.parquet"


label:
  mode: "single"          # ← 두 단계 라벨 사용
  total_col: "essay_scoreT_avg"
  total_quantile: 0.85       # 총점 상위 15%를 우수로 간주
  rubric_eq: 3.0             # 그 중 문법=3점만 양성
  min_pos: 1000              # 양성이 너무 적으면 q를 0.05씩 낮추어 확보


# 상위 집단 정의
top_select: "eq"
top_value: 3.0
# quantile 쓰려면:
# top_select: "quantile"
# q_top: 0.8

# Teacher 점수 파싱
teacher_parser:
  parse: True
  source_col: "essay_score_avg"
  delimiter: "#"
  rubric_names: "grammar, vocabulary, sentence_expression,
    intra_paragraph_structure, inter_paragraph_structure,
    structural_consistency, length, topic_clarity, originality,
    prompt_comprehension, narrative"

# 하위 모듈 공통
rho_thresh: 0.90        # 셀 내부 패밀리 병합 강도(다양성↑ 위해 0.90 권장)
seed: 42
downcast: True

# TYPE 버킷 (정규식 우선순위, 첫 매치만)
feature_grouping:
  families:
    - {name: "NDW",          patterns: ["^NDW_"] }
    - {name: "TTR",          patterns: ["^ttr_"] }
    - {name: "Adjacency",    patterns: ["^adjacency_"] }
    - {name: "SentenceRep",  patterns: ["^sentenceLvlRep_"] }
    - {name: "BasicDensity", patterns: ["^basic_density_"] }
    - {name: "BasicCount",   patterns: ["^basic_count_"] }
    - {name: "Readability",  patterns: ["^readability_"] }
    - {name: "Similarity",   patterns: ["^similarity_"] }
    - {name: "Length",       patterns: ["^sentenceLvl_.*(Len|paraLen|sentLen)", "^basic_level_.*Len"] }

# GRID (버킷 로컬 예선)
grid:
  enable: true
  local_scoring: true
  mode: "both"         # pos | type | both | pos_type
  top_per_cell: 5
  skip_cell_min: 6
  final_max_seed: 200
  partial_gate: true          
  partial_min: 0.06           


# FINAL (시드만 결승)
final:
  refit: true
  l1_subsamples: 160
  l1_C: 0.7
  rho_thresh: 0.9
  keep_top: 10
  min_auc: 0.52        
  min_partial_rho: 0.045
